<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step?,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*,Summary,ActionMaintenanceSummary*,NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?)>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="QuickTest Professional" productVer="10.00" os="" host="HAI-PC"><DocLocation><![CDATA[E:\srinew\Folder\Test Script\practice1.mts]]></DocLocation></General>
<Doc rID="T1"   productName= "QuickTest Professional"  >
<DName><![CDATA[practice1.mts]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table">
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:16]]></Time>
<TimeTick>1453224616</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:16]]></Time>
<TimeTick>1453224616</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ Agent Name: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["lakshmi"]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:16]]></Time>
<TimeTick>1453224616</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" Source="Action1" SourceLine="11" >
<Disp><![CDATA[[ Agent Name: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ Login ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", 2, "Login", 20000]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:36]]></Time>
<TimeTick>1453224636</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" status="Warning" Source="Action1" SourceLine="12" >
<Disp><![CDATA[[ Login ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ Password: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:36]]></Time>
<TimeTick>1453224636</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" Source="Action1" SourceLine="13" >
<Disp><![CDATA[[ Password: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:46]]></Time>
<TimeTick>1453224646</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" Source="Action1" SourceLine="15" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ Flight Reservation ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:50]]></Time>
<TimeTick>1453224650</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ Flight Reservation ].Close]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2016 - 23:00:15" eTime="1/19/2016 - 23:00:50" passed="1" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Warning" >
<Disp><![CDATA[practice1.mts Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T12" iterID="2" >
<Action rID="T13">
<AName><![CDATA[Action1]]></AName>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:51]]></Time>
<TimeTick>1453224651</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:51]]></Time>
<TimeTick>1453224651</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="28" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Agent Name: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["lakshmi"]]></Details>
<Time><![CDATA[1/19/2016 - 23:00:51]]></Time>
<TimeTick>1453224651</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="31" Source="Action1" SourceLine="11" >
<Disp><![CDATA[[ Agent Name: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Login ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", 2, "Login", 20000]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:11]]></Time>
<TimeTick>1453224671</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="33" status="Warning" Source="Action1" SourceLine="12" >
<Disp><![CDATA[[ Login ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Password: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:11]]></Time>
<TimeTick>1453224671</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="35" Source="Action1" SourceLine="13" >
<Disp><![CDATA[[ Password: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:21]]></Time>
<TimeTick>1453224681</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" Source="Action1" SourceLine="15" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Flight Reservation ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:27]]></Time>
<TimeTick>1453224687</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ Flight Reservation ].Close]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2016 - 23:00:50" eTime="1/19/2016 - 23:01:27" passed="1" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="25" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="24" status="Warning" >
<Disp><![CDATA[practice1.mts Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T21" iterID="3" >
<Action rID="T22">
<AName><![CDATA[Action1]]></AName>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:27]]></Time>
<TimeTick>1453224687</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:27]]></Time>
<TimeTick>1453224687</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="47" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[Run "C:\Program Files\HP\QuickTest Professional\samples\flight\app\flight4a.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="46" status="Passed" Source="Action1" SourceLine="10" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Agent Name: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["lakshmi"]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:27]]></Time>
<TimeTick>1453224687</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" Source="Action1" SourceLine="11" >
<Disp><![CDATA[[ Agent Name: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Login ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["text", 2, "Login", 20000]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:48]]></Time>
<TimeTick>1453224708</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="51" status="Warning" Source="Action1" SourceLine="12" >
<Disp><![CDATA[[ Login ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ Password: ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["mercury"]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:48]]></Time>
<TimeTick>1453224708</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="53" Source="Action1" SourceLine="13" >
<Disp><![CDATA[[ Password: ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ OK ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:01:58]]></Time>
<TimeTick>1453224718</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="55" Source="Action1" SourceLine="15" >
<Disp><![CDATA[[ OK ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ Flight Reservation ].Close]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[1/19/2016 - 23:02:02]]></Time>
<TimeTick>1453224722</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" Source="Action1" SourceLine="19" >
<Disp><![CDATA[[ Flight Reservation ].Close]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="1/19/2016 - 23:01:27" eTime="1/19/2016 - 23:02:02" passed="1" failed="0" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="43" status="Warning" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="42" status="Warning" >
<Disp><![CDATA[practice1.mts Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="1/19/2016 - 23:00:15" eTime="1/19/2016 - 23:02:02" passed="3" failed="0" warnings="3" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Warning" >
<Disp><![CDATA[Test practice1.mts Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>